### ISSUE TITLE
[BUG] Channel rewards not working

### ISSUE THREAD

**Issue by DhannyCC** [VirtualZer0/TwitchKeyboard#2]
I tried to use channel rewards but it doesn't work for me.

**Comment by VirtualZer0** [comment]
Can you attach a screenshot of the rule configuration window?

**Comment by DhannyCC** [comment]
![descarga](https://user-images.githubusercontent.com/103536753/187262065-9364bab3-5e9d-4c63-96cc-5cdd04aaf887.png)

**Comment by VirtualZer0** [comment]
Try making a reward with specific text. Will it work? Also just in case, check that the application has an active connection status during the test.

**Comment by DhannyCC** [comment]
Reward with text, if it works. but if you don't have it, ask for a text no.

**Comment by VirtualZer0** [comment]
I think I can fix that within half an hour. I'll notify you here when the update is ready.

**Comment by DhannyCC** [comment]
Thank you very much, this application will be very helpful.

**Comment by VirtualZer0** [comment]
It looks like Twitch has changed its API and now any awards without messages are only visible through a separate service that requires authorization. At the moment there is no authorization in the app, so it will take me some time to implement it. For now I will leave this issue open until this problem is solved. This solution will require some work.

**Comment by VirtualZer0** [comment]
I was a little hasty. It looks like there is a solution after all.

**Comment by VirtualZer0** [comment]
Try this pre-release: https://github.com/VirtualZer0/TwitchKeyboard/releases/tag/1.0.3-rc.2

Don't forget to download new .NET version

**Comment by DhannyCC** [comment]
It works perfect
